#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: redwood-web
  type: web
  env: static
  buildCommand: corepack enable | yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 18
  - key: SKIP_INSTALL_DEPS
    value: true
  routes:
  - type: rewrite
    source: /.redwood/functions/*
#####
# NOTE: replace destination api url after first deploy to Render
# example:
#   destination: https://myredwoodproject-api.onrender.com/*
#####
    destination: https://redwood-api-blgm.onrender.com/*
  - type: rewrite
    source: /*
    destination: /200.html

- name: redwood-api
  type: web
  plan: free
  env: node
  region: oregon
  preDeployCommand: corepack enable
  buildCommand: corepack enable | yarn && yarn rw build api
  startCommand: corepack enable | yarn rw deploy render api --database none
  envVars:
  - key: NODE_VERSION
    value: 18

